version: "3.8"
services:
  frepple:
    image: ghcr.io/frepple/frepple-community:latest
    container_name: frepple-community-local
    ports:
      - "9000:80"
    environment:
      POSTGRES_HOST: "host.docker.internal"
      POSTGRES_PORT: 5432
      POSTGRES_USER: "frepple"
      POSTGRES_PASSWORD: "frepple"
      POSTGRES_DBNAME: "frepple"
      FREPPLE_DATE_STYLE_WITH_HOURS: "false"
      FREPPLE_TIME_ZONE: "UTC"
      FREPPLE_THEMES: "earth grass lemon odoo openbravo orange snow strawberry water"
      FREPPLE_DEFAULT_THEME: "earth"
      FREPPLE_EMAIL_USE_TLS: "true"
      FREPPLE_DEFAULT_FROM_EMAIL: "walkercpt@gmail.com"
      FREPPLE_SERVER_EMAIL: "walkercpt@gmail.com"
      FREPPLE_EMAIL_HOST_USER: "walkercpt@gmail.com"
      FREPPLE_EMAIL_HOST_PASSWORD: "frePPLeIsTheBest"
      FREPPLE_EMAIL_HOST: ""
      FREPPLE_EMAIL_PORT: 25
      FREPPLE_CONTENT_SECURITY_POLICY: "frame-ancestors 'self'"
      FREPPLE_X_FRAME_OPTIONS: "SAMEORIGIN"
      FREPPLE_CSRF_TRUSTED_ORIGINS: ""
      FREPPLE_SECURE_PROXY_SSL_HEADER: ""
      FREPPLE_SESSION_COOKIE_SECURE: "false"
      FREPPLE_CSRF_COOKIE_SAMESITE: "lax"
      FREPPLE_FTP_PROTOCOL: "SFTP"
      FREPPLE_FTP_HOST: ""
      FREPPLE_FTP_PORT: 22
      FREPPLE_FTP_USER: ""
      FREPPLE_FTP_PASSWORD: ""
      FREPPLE_AUTOSTART_WEBSERVICE: ""  # List of scenarios for which to automatically start the web service, separated by space

    volumes:
      - ./frepple-config:/etc/frepple
      - ./frepple-logs:/var/log/frepple
      - ./apache-logs:/var/log/apache2
    restart: always