services:
  appsmith:
    image: appsmith/appsmith-ce:release
    container_name: appsmith
    ports:
      - "8080:80"
    environment:
      APPSMITH_ENCRYPTION_PASSWORD: abcd
      APPSMITH_ENCRYPTION_SALT: abcd
    volumes:
      - appsmith-stacks:/appsmith-stacks
    restart: unless-stopped

  aps-backend:
    build: ./aps_backend  # Or use image: your-backend-image
    container_name: aps-backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgresUser
      - POSTGRES_PASSWORD=postgresPass
      - POSTGRES_DB=postgresDB
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: apache/age:release_PG15_1.6.0
    # image: apache/age:release_PG17_1.6.0
    container_name: postgres
    environment:
      POSTGRES_USER: postgresUser
      POSTGRES_PASSWORD: postgresPass
      POSTGRES_DB: postgresDB
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
  appsmith-stacks: